

server:
  port: 8081

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.use.type.headers: false
      spring.json.trusted.packages: "com.paypal.notification_service.entity"
      spring.json.value.default.type: com.paypal.notification_service.entity.Transaction

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true